// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using bg_lib.Data;

#nullable disable

namespace bg_lib.Migrations
{
    [DbContext(typeof(bg_libContext))]
    [Migration("20241107193209_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.10");

            modelBuilder.Entity("bg_lib.Models.Game", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<int>("IsCheckedOut")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IsInCirculation")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IsPlayToWin")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastCheckinDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastCheckoutDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Game");
                });
#pragma warning restore 612, 618
        }
    }
}
